- name: Check latest files in directory
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check EDAA files
      find:
       paths: "/appinterface/remanagement/reports/edaa"
       recurse: no
       file_type: file
      register: found_files

    - name: Show the files and directories created today
      debug:
       msg: "{{ found_files.files | json_query('[].path') | map('basename') | list }}"
