- name: Health check script started.
  hosts: localhost
  gather_facts: no
  vars:
    task_counter: 1
  tasks:
    - name:  1.Checking EDAA files
      shell: "ls -altrh /home/Akula/ --time-style=+%D | grep $(date +%D)"
      register: "files"

    - name: Latest files
      debug:
       msg: "{{ files.stdout_lines }}"
 
    - block:
      - name: 2.Checking Docker service
        ansible.builtin.systemd:
         name: docker
         state: started
        register: docker
        ignore_errors: yes

      - name: Docker service status
        debug:
         msg: "Docker service is running"
        when: docker.status.SubState == "running"

      rescue:
      - name: Docker service status
        debug:
         msg: docker.status.SubState != "running"
      
    - name: 3.Check if Docker container is running
      shell: docker ps
      register: docker
      ignore_errors: yes

    - name: Dokcer containers status
      debug:
        msg: "{{ docker.stdout_lines }}"

    - block:
      - name: 4.Check if bookBulkProcessor process is running
        command: pgrep -f "bookBulkProcessor"
        register: bookBulkProcessor_check
        ignore_errors: yes

      - name: BookBulkProcessor process status
        debug:
         msg: "BookBulkProcessor process is running!"
        when: bookBulkProcessor_check.stdout != ""

      rescue:
      - name: BookBulkProcessor process status
        debug:
         msg: "BookBulkProcessor process is NOT running."
        when: bookBulkProcessor_check.stdout == ""

    - block:
      - name: 5.Check if OnlineReportGenerator is running
        ansible.builtin.command: pgrep -f "OnlineReportGenerator"
        register: OnlineReportGenerator_check
        ignore_errors: yes

      - name: OnlineReportGenerator process status
        debug:
         msg: "OnlineReportGenerator is running."
        when: OnlineReportGenerator_check.stdout != ""

      rescue:
      - name: OnlineReportGenerator process status
        debug:
         msg: "OnlineReportGenerator process is NOT running."
        when: OnlineReportGenerator_check.stdout == ""

    - block:
      - name: 6.Check if Kafka zookeeper process is running
        shell: pgrep -af java | grep -o '\S*zookeeper.properties\S*'
        register: zookeeper_check
        ignore_errors: yes

      - name: Kafka zookeeper process status
        debug:
         msg: "Kafka zookeeper process is running!"
        when: zookeeper_check.stdout != ""

      rescue:
      - name: Kafka zookeeper process status
        debug:
         msg: "Kafka zookeeper process is NOT running."
        when: zookeeper_check.stdout == 


    - block:
      - name: 7.Check if Kafka broker  process is running
        shell: pgrep -af java | grep -o '\S*server.properties\S*'
        register: server_check
        ignore_errors: yes

      - name: Kafka process status
        debug:
         msg: "Kafka broker process is running!"
        when: server_check.stdout != ""

      rescue:
      - name: Kafka process status
        debug:
         msg: "Kafka broker process is NOT running."
        when: server_check.stdout == ""

