- name: Book Process
  hosts: localhost
  gather_facts: false
  tasks:
  - block:
      - name: Check if bookBulkProcessor process is running
        command: pgrep -f "bookBulkProcessor"
        register: bookBulkProcessor_check
        ignore_errors: yes

      - name: Report if bookBulkProcessor process is running
        debug:
         msg: "The bookBulkProcessor process is running!"
        when: bookBulkProcessor_check.stdout != ""

    rescue: 
      - name: Report if bookBulkProcessor is not running
        debug:
         msg: "The bookBulkProcessor process is NOT running."
        when: bookBulkProcessor_check.stdout == ""
