---
- name: Get Docker logs and save to a file
  hosts: localhost
  tasks:
    - name: Run the command to get logs with error filter and save to file
      shell: "sudo docker logs mainmarket-fixprocessor1 --since=2024-11-04 2>&1 | grep -i warn > /home/Phani/Docker_output_file.txt"
      ignore_errors: yes  # Optional: Allows the playbook to continue even if this command fails

    - name: Show message after logs are saved
      debug:
        msg: "Docker logs with errors have been saved to /home/Phani/Docker_output_file.txt"

