- name: Check if Docker_container_status process is running
  hosts: localhost
  tasks:
    - name: Check if Docker container is running
      shell: docker ps
      register: docker
      ignore_errors: yes

    - name: Show the container names and statuses
      debug:
        msg: "{{ docker.stdout_lines }}"
