- name: Check latest files in directory
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if zookeeper process is running
      shell: pgrep -af java | grep -o '\S*zookeeper.properties\S*'
      register: zookeeper_check
      ignore_errors: yes

    - name: Check if server process is running
      shell: pgrep -af java | grep -o '\S*server.properties\S*'
      register: server_check
      ignore_errors: yes

    - name: Report if zookeeper process is running
      debug:
        msg: "The zookeeper process is running!"
      when: zookeeper_check.stdout != ""

    - name: Report if server process is running
      debug:
        msg: "The server process is running!"
      when: server_check.stdout != ""

    - name: Report if zookeeper is not running
      debug:
        msg: "The zookeeper process is NOT running."
      when: zookeeper_check.stdout == ""

    - name: Report if server is not running
      debug:
        msg: "The server process is NOT running."
      when: server_check.stdout == ""
